{% set version = "1.8" %}
{% set name = "libntlm" %}
{% set sha256 = "91de864224913b9493c7a6cec2890e6eded3610d34c3d983132823de348ec2ca" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://gitlab.com/gsasl/libntlm/-/archive/v{{ version }}/libntlm-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # This package is a dependency of libhdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage("libntlm", max_pin="x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make

test:
  commands:
    - test -f $PREFIX/include/ntlm.h
    - test -f $PREFIX/lib/libntlm.a
    - test -f $PREFIX/lib/libntlm{{ SHLIB_EXT }}
    - test -f $PREFIX/lib/pkgconfig/libntlm.pc

about:
  home: http://www.nongnu.org/libntlm/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Improved implementation of Microsoft's NTLM authentication

extra:
  recipe-maintainers:
    - mariusvniekerk
    - martindurant
