appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: lVb4diEAtCmyZx6/4W76cAltVsAFDCxzZTe+oC1fgqCxVRX+0ibYcqQB6BdJVnsqh3KDBnD32RB5483wsJrhwA1jSJfHOfMeoY0ZpeRYheIkdiLivTJoxQJDwlXIriV0yUBGp2M/beN1LD41cNgAAle1l/IdVVdC54j4AMfSHBicCS48unUOyKsPz9LHmOvpzp5IkR8fMr5XDppcIJouABsM7YF1WMUEf+BVWhoVeVdyPIVrpnzqy0pn5guptrEqJukmoBC79OTi6avU/GGT//mfioCodz3PE/zxodQla1JgU8nbY6qAM9FJGaAeow1ZFAsqOurLblAB6v8hfVFAE4P8N+3AHPKdj/e21AZ8AqHKAJEZYYPwDHqKKe4XgtfkYVlbfU3/1LuqxtsXqp7j033h0wovMpBkXGSXjYgRQDaODnQudB7HKuGaASnIK61SeJiXnEiKVuV38n1sp2IQsQXa/YGl+G2py2RRsCc9VwduaKhHLPd2ZnDne3Pl2zNdIRoCeMWq//6H/JUY8G4vgM5NlLJ3V34wefBw6/VKB4/FNAQoIY/KPoKzb+vH50o0JY1ozYKkgtAz5cG8Epd/q21SpgqOzh7kD9/s08eBqChVo3Kl5hv8MdDCsfuTMIhoLx8LKcaBA7P0u6XtVRy0w7gmktQtOM00oaOdx9qZEdY=}
conda_forge_output_validation: true
